# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Paro/Documents/Vivado/minisys/minisys.srcs/sources_1/ip/vram/vram.xci
# IP: The module: 'vram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paro/Documents/Vivado/minisys/minisys.gen/sources_1/ip/vram/vram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Paro/Documents/Vivado/minisys/minisys.srcs/sources_1/ip/vram/vram.xci
# IP: The module: 'vram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Paro/Documents/Vivado/minisys/minisys.gen/sources_1/ip/vram/vram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
